const placesMap = new Map([
  ["asia", { vi: "Châu Á", en: "Asia" }],
  ["africa", { vi: "Châu Phi", en: "Africa" }],
  ["oceania", { vi: "Châu Úc", en: "Oceania" }],
  ["america", { vi: "Châu Mỹ", en: "America" }],
  ["northern", { vi: "Miền Bắc", en: "Northern" }],
  ["southern", { vi: "Miền Nam", en: "Southern" }],
  ["western", { vi: "Miền Tây", en: "Southwest" }],
  ["eastern", { vi: "Miền Đông", en: "Southeast" }],
  ["central", { vi: "Miền Trung", en: "Central" }],
  ["an-giang", { vi: "An Giang", en: "An Giang" }],
  ["ba-ria-vung-tau", { vi: "Bà Rịa - Vũng Tàu", en: "Ba Ria" }],
  ["bac-lieu", { vi: "Bạc Liêu", en: "Bac Lieu" }],
  ["bac-kan", { vi: "Bắc Kạn", en: "Bac Kan" }],
  ["bac-giang", { vi: "Bắc Giang", en: "Bac Giang" }],
  ["bac-ninh", { vi: "Bắc Ninh", en: "Bac Ninh" }],
  ["ben-tre", { vi: "Bến Tre", en: "Ben Tre" }],
  ["binh-duong", { vi: "Bình Dương", en: "Binh Duong" }],
  ["binh-dinh", { vi: "Bình Định", en: "Binh Dinh" }],
  ["binh-phuoc", { vi: "Bình Phước", en: "Binh Phuoc" }],
  ["binh-thuan", { vi: "Bình Thuận", en: "Binh Thuan" }],
  ["ca-mau", { vi: "Cà Mau", en: "Ca Mau" }],
  ["cao-bang", { vi: "Cao Bằng", en: "Cao Bang" }],
  ["can-tho", { vi: "Cần Thơ", en: "Can Tho" }],
  ["da-nang", { vi: "Đà Nẵng", en: "Da Nang" }],
  ["dak-lak", { vi: "Đăk-Lăk", en: "DakLak" }],
  ["dak-nong", { vi: "Đăk-Nông", en: "DakNong" }],
  ["dien-bien", { vi: "Điện Biên", en: "Dien Bien" }],
  ["dong-nai", { vi: "Đồng Nai", en: "Dong Nai" }],
  ["dong-thap", { vi: "Đồng Tháp", en: "Dong Thap" }],
  ["gia-lai", { vi: "Gia Lai", en: "Gia Lai" }],
  ["ha-giang", { vi: "Hà Giang", en: "Ha Giang" }],
  ["ha-nam", { vi: "Hà Nam", en: "Ha Nam" }],
  ["ha-noi", { vi: "Hà Nội", en: "Ha Noi" }],
  ["ha-tay", { vi: "Hà Tây", en: "Ha Tay" }],
  ["ha-tinh", { vi: "Hà Tĩnh", en: "Ha Tinh" }],
  ["hai-duong", { vi: "Hải Dương", en: "Hai Duong" }],
  ["hai-phong", { vi: "Hải Phòng", en: "Hai Phong" }],
  ["hoa-binh", { vi: "Hòa Bình", en: "Hoa Binh" }],
  ["ho-chi-minh", { vi: "Hồ Chí Minh", en: "Ho Chi Minh" }],
  ["hau-giang", { vi: "Hậu Giang", en: "Hau Giang" }],
  ["hung-yen", { vi: "Hưng Yên", en: "Hung Yen" }],
  ["khanh-hoa", { vi: "Khánh Hòa", en: "Khanh Hoa" }],
  ["kien-giang", { vi: "Kiên Giang", en: "Kien Giang" }],
  ["kon-tum", { vi: "Kon Tum", en: "Kon Tum" }],
  ["lai-chau", { vi: "Lai Châu", en: "Lai Chau" }],
  ["lao-cai", { vi: "Lào Cai", en: "Lao Cai" }],
  ["lang-son", { vi: "Lạng Sơn", en: "Lang Son" }],
  ["lam-dong", { vi: "Lâm Đồng", en: "Lam Dong" }],
  ["long-an", { vi: "Long An", en: "Long An" }],
  ["nam-dinh", { vi: "Nam Định", en: "Nam Dinh" }],
  ["nghe-an", { vi: "Nghệ An", en: "Nghe An" }],
  ["ninh-binh", { vi: "Ninh Bình", en: "Ninh Binh" }],
  ["ninh-thuan", { vi: "Ninh Thuận", en: "Ninh Thuan" }],
  ["phu-tho", { vi: "Phú Thọ", en: "Phu Tho" }],
  ["phu-yen", { vi: "Phú Yên", en: "Phu Yen" }],
  ["quang-binh", { vi: "Quảng Bình", en: "Quang Binh" }],
  ["quang-nam", { vi: "Quảng Nam", en: "Quang Nam" }],
  ["quang-ngai", { vi: "Quảng Ngãi", en: "Quang Ngai" }],
  ["quang-ninh", { vi: "Quảng Ninh", en: "Quang Ninh" }],
  ["quang-tri", { vi: "Quảng Trị", en: "Quang Tri" }],
  ["soc-trang", { vi: "Sóc Trăng", en: "Soc Trang" }],
  ["son-la", { vi: "Sơn La", en: "Son La" }],
  ["tay-ninh", { vi: "Tây Ninh", en: "Tay Ninh" }],
  ["thai-binh", { vi: "Thái Bình", en: "Thai Binh" }],
  ["thai-nguyen", { vi: "Thái Nguyên", en: "Thai Nguyen" }],
  ["thanh-hoa", { vi: "Thanh Hóa", en: "Thanh Hoa" }],
  ["hue", { vi: "Thừa Thiên - Huế", en: "Thua Thien - Hue" }],
  ["tien-giang", { vi: "Tiền Giang", en: "Tien Giang" }],
  ["tra-vinh", { vi: "Trà Vinh", en: "Tra Vinh" }],
  ["tuyen-quang", { vi: "Tuyên Quang", en: "Tuyen Quang" }],
  ["vinh-long", { vi: "Vĩnh Long", en: "Vinh Long" }],
  ["vinh-phuc", { vi: "Vĩnh Phúc", en: "Vinh Phuc" }],
  ["yen-bai", { vi: "Yên Bái", en: "Yen Bai" }],
  ["vietnam", { vi: "Việt Nam", en: "Viet Nam" }],
  ["russia", { vi: "Nga", en: "Russia" }],
  ["germany", { vi: "Đức", en: "Germany" }],
  ["united-kingdom", { vi: "Anh", en: "England" }],
  ["france", { vi: "Pháp", en: "France" }],
  ["italy", { vi: "Ý", en: "Italy" }],
  ["spain", { vi: "Tây Ban Nha", en: "Spain" }],
  ["ukraine", { vi: "Ukraine", en: "Ukraine" }],
  ["poland", { vi: "Ba Lan", en: "Poland" }],
  ["romania", { vi: "Romania", en: "Romania" }],
  ["netherlands", { vi: "Hà Lan", en: "Netherlands" }],
  ["belgium", { vi: "Bỉ", en: "Belgium" }],
  ["czechia", { vi: "Cộng hòa Séc", en: "Czech" }],
  ["greece", { vi: "Hy Lạp", en: "Greece" }],
  ["portugal", { vi: "Bồ Đào Nha", en: "Portugal" }],
  ["sweden", { vi: "Thụy Điển", en: "Sweden" }],
  ["hungary", { vi: "Hungary", en: "Hungary" }],
  ["belarus", { vi: "Belarus", en: "Belarus" }],
  ["austria", { vi: "Áo", en: "Austria" }],
  ["serbia", { vi: "Xéc-bi-a", en: "Serbia" }],
  ["switzerland", { vi: "Thụy Sỹ", en: "Switzerland" }],
  ["bulgaria", { vi: "Bulgaria", en: "Bulgaria" }],
  ["denmark", { vi: "Đan Mạch", en: "Denmark" }],
  ["finland", { vi: "Phần Lan", en: "Finland" }],
  ["slovakia", { vi: "Slovakia", en: "Slovakia" }],
  ["norway", { vi: "Na Uy", en: "Norway" }],
  ["ireland", { vi: "Ireland", en: "Ireland" }],
  ["croatia", { vi: "Croatia", en: "Croatia" }],
  ["moldova", { vi: "Moldova", en: "Moldova" }],
  [
    "bosnia-herzegovina",
    { vi: "Bosnia và Herzegovina", en: "Bosnia and Herzegovina" },
  ],
  ["albania", { vi: "Albania", en: "Albania" }],
  ["lithuania", { vi: "Litva", en: "Litva" }],
  ["north-macedonia", { vi: "North Macedonia", en: "North Macedonia" }],
  ["slovenia", { vi: "Slovenia", en: "Slovenia" }],
  ["latvia", { vi: "Latvia", en: "Latvia" }],
  ["kosovo", { vi: "Kosovo", en: "Kosovo" }],
  ["estonia", { vi: "Estonia", en: "Estonia" }],
  ["montenegro", { vi: "Montenegro", en: "Montenegro" }],
  ["luxembourg", { vi: "Lúc-xăm-bua", en: "Luxembourg" }],
  ["malta", { vi: "Malta", en: "Malta" }],
  ["iceland", { vi: "Iceland", en: "Iceland" }],
  ["andorra", { vi: "Andorra", en: "Andorra" }],
  ["monaco", { vi: "Monaco", en: "Monaco" }],
  ["liechtenstein", { vi: "Liechtenstein", en: "Liechtenstein" }],
  ["san-marino", { vi: "San Marino", en: "San Marino" }],
  ["holy-see", { vi: "Holy See", en: "Holy See" }],
]);

export default placesMap;
