const placesMap = new Map([
  ["asia", "Châu Á"],
  ["africa", "Châu Phi"],
  ["oceania", "Châu Úc"],
  ["america", "Châu Mỹ"],
  ["northern", "Miền Bắc"],
  ["southern", "Miền Nam"],
  ["western", "Miền Tây"],
  ["eastern", "Miền Đông"],
  ["central", "Miền Trung"],
  ["an-giang", "An Giang"],
  ["ba-ria-vung-tau", "Bà Rịa - Vũng Tàu"],
  ["bac-lieu", "Bạc Liêu"],
  ["bac-kan", "Bắc Kạn"],
  ["bac-giang", "Bắc Giang"],
  ["bac-ninh", "Bắc Ninh"],
  ["ben-tre", "Bến Tre"],
  ["binh-duong", "Bình Dương"],
  ["binh-dinh", "Bình Định"],
  ["binh-phuoc", "Bình Phước"],
  ["binh-thuan", "Bình Thuận"],
  ["ca-mau", "Cà Mau"],
  ["cao-bang", "Cao Bằng"],
  ["can-tho", "Cần Thơ"],
  ["da-nang", "Đà Nẵng"],
  ["dak-lak", "Đăk-Lăk"],
  ["dak-nong", "Đăk-Nông"],
  ["dien-bien", "Điện Biên"],
  ["dong-nai", "Đồng Nai"],
  ["dong-thap", "Đồng Tháp"],
  ["gia-lai", "Gia Lai"],
  ["ha-giang", "Hà Giang"],
  ["ha-nam", "Hà Nam"],
  ["ha-noi", "Hà Nội"],
  ["ha-tay", "Hà Tây"],
  ["ha-tinh", "Hà Tĩnh"],
  ["hai-duong", "Hải Dương"],
  ["hai-phong", "Hải Phòng"],
  ["hoa-binh", "Hòa Bình"],
  ["ho-chi-minh", "Hồ Chí Minh"],
  ["hau-giang", "Hậu Giang"],
  ["hung-yen", "Hưng Yên"],
  ["khanh-hoa", "Khánh Hòa"],
  ["kien-giang", "Kiên Giang"],
  ["kon-tum", "Kon Tum"],
  ["lai-chau", "Lai Châu"],
  ["lao-cai", "Lào Cai"],
  ["lang-son", "Lạng Sơn"],
  ["lam-dong", "Lâm Đồng"],
  ["long-an", "Long An"],
  ["nam-dinh", "Nam Định"],
  ["nghe-an", "Nghệ An"],
  ["ninh-binh", "Ninh Bình"],
  ["ninh-thuan", "Ninh Thuận"],
  ["phu-tho", "Phú Thọ"],
  ["phu-yen", "Phú Yên"],
  ["quang-binh", "Quảng Bình"],
  ["quang-nam", "Quảng Nam"],
  ["quang-ngai", "Quảng Ngãi"],
  ["quang-ninh", "Quảng Ninh"],
  ["quang-tri", "Quảng Trị"],
  ["soc-trang", "Sóc Trăng"],
  ["son-la", "Sơn La"],
  ["tay-ninh", "Tây Ninh"],
  ["thai-binh", "Thái Bình"],
  ["thai-nguyen", "Thái Nguyên"],
  ["thanh-hoa", "Thanh Hóa"],
  ["hue", "Thừa Thiên - Huế"],
  ["tien-giang", "Tiền Giang"],
  ["tra-vinh", "Trà Vinh"],
  ["tuyen-quang", "Tuyên Quang"],
  ["vinh-long", "Vĩnh Long"],
  ["vinh-phuc", "Vĩnh Phúc"],
  ["yen-bai", "Yên Bái"],
  ["vietnam", "Việt Nam"],
  ["russia", "Nga"],
  ["germany", "Đức"],
  ["united-kingdom", "Anh"],
  ["france", "Pháp"],
  ["italy", "Ý"],
  ["spain", "Tây Ban Nha"],
  ["ukraine", "Ukraine"],
  ["poland", "Ba Lan"],
  ["romania", "Romania"],
  ["netherlands", "Hà Lan"],
  ["belgium", "Bỉ"],
  ["czechia", "Cộng hòa Séc"],
  ["greece", "Hy Lạp"],
  ["portugal", "Bồ Đào Nha"],
  ["sweden", "Thụy Điển"],
  ["hungary", "Hungary"],
  ["belarus", "Belarus"],
  ["austria", "Áo"],
  ["serbia", "Xéc-bi-a"],
  ["switzerland", "Thụy Sỹ"],
  ["bulgaria", "Bulgaria"],
  ["denmark", "Đan Mạch"],
  ["finland", "Phần Lan"],
  ["slovakia", "Slovakia"],
  ["norway", "Na Uy"],
  ["ireland", "Ireland"],
  ["croatia", "Croatia"],
  ["moldova", "Moldova"],
  ["bosnia-herzegovina", "Bosnia and Herzegovina"],
  ["albania", "Albania"],
  ["lithuania", "Litva"],
  ["north-macedonia", "North Macedonia"],
  ["slovenia", "Slovenia"],
  ["latvia", "Latvia"],
  ["kosovo", "Kosovo"],
  ["estonia", "Estonia"],
  ["montenegro", "Montenegro"],
  ["luxembourg", "Lúc-xăm-bua"],
  ["malta", "Malta"],
  ["iceland", "Iceland"],
  ["andorra", "Andorra"],
  ["monaco", "Monaco"],
  ["liechtenstein", "Liechtenstein"],
  ["san-marino", "San Marino"],
  ["holy-see", "Holy See"],
]);

export default placesMap;
